- ".php"
- ".html"
- ".htm"
- ".asp"
- ".aspx"
- ".jsp"
- ".jspx"
- ".xml"
- ".ini"
- ".inc"
- ".msg"
- ".eml"
- ".pst"
- ".db"
- ".sqlite"
- ".m4v"
- ".avi"
- ".flv"
- ".mov"
- ".wmv"
- ".mp3"
- ".wav"
- ".aac"
- ".ogg"
- ".pdf"
- ".doc"
- ".ppt"
- ".xls"
- ".csv"
- ".zip"
- ".rar"
- ".7z"
- ".tar"
- ".gz"
- ".mp4"
- ".mkv"
- ".iso"
- ".jar"
- ".war"
- ".ear"
- ".apk"
- ".exe"
- ".dll"
- ".sys"
- ".bin"
- ".dat"
- ".log"
- ".conf"
- ".cfg"
- ".ini"
- ".bak"
- ".old"
- ".mdb"
- ".accdb"
- ".sql"
- ".xml"
- ".json"
- ".csv"
- ".tsv"
- ".tab"
- ".jpg"
- ".jpeg"
- ".png"
- ".gif"
- ".bmp" 