#404 Error messages. Sub domain
- name: "AWS"
  notFoundMessage: "The specified bucket does not exist"
- name: "GitHub"
  notFoundMessage: "There isn't a GitHub Pages site here"
- name: "Azure"
  notFoundMessage: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable"
- name: "Heroku"
  notFoundMessage: "No such app"
- name: "Heroku"
  notFoundMessage: "There's nothing here, yet"
- name: "Fastly"
  notFoundMessage: "Fastly error: unknown domain"
- name: "WordPress"
  notFoundMessage: "Do you want to register domain.wordpress.com"
- name: "Tumblr"
  notFoundMessage: "There's nothing here"
- name: "Shopify"
  notFoundMessage: "Sorry, this shop is currently unavailable"
- name: "Bitbucket"
  notFoundMessage: "Repository not found"
- name: "Cloudfront"
  notFoundMessage: "ERROR: The request could not be satisfied"
- name: "Ghost"
  notFoundMessage: "The thing you were looking for is no longer here, or never was"
- name: "Read the Docs"
  notFoundMessage: "The requested project does not exist"
